/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_test_nativeLib_Lib */

#ifndef _Included_JNI_test_nativeLib_Lib
#define _Included_JNI_test_nativeLib_Lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI_test_nativeLib_Lib
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JNI_1test_nativeLib_Lib_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
